Add Support for WP Uninstall
josegonzalez/dokku-wordpress pull request #1
Opened 2016-11-26 17:57 UTC by kjschulz

@josegonzalez, this doesn't execute properly just yet.  Thought I was using the same syntax you did but I'm missing something.  Mind to take a look when you get a chance?  Upon execution I get the following error and I'm not sure what I'm doing wrong: `make: *** No rule to make target `destroy'.  Stop.`

2016-11-26 18:40 UTC, kjschulz commented
Also @josegonzalez, just tried these commands manually and it seems that the `-force` flag for `apps:destroy` isn't recognized (i'm on dokku 7.2).  And it would seem that if we do destroy the app, unmounting of the storage dirs is unnecessary...we only need to `rm` them on the server.  You agree?  If so I'll make that change and push as well...

2016-11-26 18:52 UTC, josegonzalez commented
It's two dashes, not one.

2016-11-26 19:31 UTC, kjschulz commented
Ok, should be all good to go now 🎉

2016-11-29 01:27 UTC, josegonzalez requested changes

2016-11-29 01:27 UTC, josegonzalez commented on Makefile
> +	$(DOKKU_CMD) mysql:unlink $(APP_NAME)-database $(APP_NAME)
This  assumes unattended. Can you also create the alternative when its not unattended?

2016-11-29 23:07 UTC, josegonzalez commented on Makefile
> +	$(DOKKU_CMD) mysql:unlink $(APP_NAME)-database $(APP_NAME)
Specifically, we should have a version that echos out the commands to run.

2016-11-29 23:10 UTC, kjschulz commented
Yep, will try and do this tonight or tomorrow.  Thanks.

2016-11-29 23:11 UTC, kjschulz commented on Makefile
> +	$(DOKKU_CMD) mysql:unlink $(APP_NAME)-database $(APP_NAME)
Yep, will try and do this tonight/tomorrow.

2016-12-09 13:29 UTC, kjschulz commented on Makefile
> +	$(DOKKU_CMD) mysql:unlink $(APP_NAME)-database $(APP_NAME)
@josegonzalez, made the change.

2016-12-09 17:39 UTC, josegonzalez approved these changes

2016-12-09 17:39 UTC, merged